# Use the Ubuntu base image
FROM node:18

# Set the working directory for your app
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Copy the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Make the script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
# Expose the port your app runs on
EXPOSE 8000


ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]